/* The following code was generated by JFlex 1.4.3 on 12/8/17 1:59 PM */

/* Specification for Fractal tokens */

// user customisations

package fractal.syntax;
import java_cup.runtime.*;
import fractal.sys.FractalException;
import fractal.sys.FractalLexerException;

// JFlex directives
    

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/8/17 1:59 PM from the specification file
 * <tt>FractalLexer.jflex</tt>
 */
public class FractalLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\2\1\2\1\7\1\0\1\2\1\1\22\0\1\2\1\52"+
    "\3\0\1\13\2\0\1\43\1\44\1\12\1\10\1\26\1\11\1\4"+
    "\1\6\12\3\1\17\1\0\1\15\1\16\1\14\1\5\1\51\32\5"+
    "\1\45\1\0\1\46\1\0\1\5\1\0\1\22\1\30\1\42\1\24"+
    "\1\33\1\27\1\35\1\36\1\34\1\5\1\31\1\32\1\41\1\23"+
    "\1\20\1\37\1\5\1\21\1\47\1\25\1\40\1\50\4\5\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\5\5\1\17\7\5\1\20\1\21\1\22\1\23\1\5"+
    "\1\24\1\25\1\26\1\27\1\30\6\5\1\31\1\32"+
    "\3\5\1\33\1\34\3\5\1\26\1\0\4\5\1\35"+
    "\1\36\1\37\2\5\1\40\11\5\1\41\1\42\1\5"+
    "\1\43\1\44\3\5\1\45\1\5\1\46\1\47\1\50"+
    "\2\5\1\51\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\53\0\53\0\126\0\201\0\254\0\327"+
    "\0\53\0\53\0\53\0\53\0\53\0\53\0\53\0\53"+
    "\0\u0102\0\u012d\0\u0158\0\u0183\0\u01ae\0\53\0\u01d9\0\u0204"+
    "\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\53\0\53\0\53"+
    "\0\53\0\u0306\0\53\0\53\0\u0331\0\u035c\0\254\0\u0387"+
    "\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\254\0\254\0\u0489"+
    "\0\u04b4\0\u04df\0\254\0\254\0\u050a\0\u0535\0\u0560\0\u058b"+
    "\0\201\0\u05b6\0\u05e1\0\u060c\0\u0637\0\254\0\254\0\254"+
    "\0\u0662\0\u068d\0\254\0\u06b8\0\u06e3\0\u070e\0\u0739\0\u0764"+
    "\0\u078f\0\u07ba\0\u07e5\0\u0810\0\254\0\254\0\u083b\0\254"+
    "\0\254\0\u0866\0\u0891\0\u08bc\0\254\0\u08e7\0\254\0\254"+
    "\0\254\0\u0912\0\u093d\0\254\0\254";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\3"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\7\1\26\1\27"+
    "\1\30\1\7\1\31\1\32\2\7\1\33\1\34\2\7"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\7\1\43"+
    "\1\44\56\0\1\5\1\45\51\0\1\45\52\0\1\7"+
    "\1\0\1\7\12\0\6\7\1\0\14\7\4\0\2\7"+
    "\10\0\1\46\47\0\1\7\1\0\1\7\12\0\1\7"+
    "\1\47\4\7\1\0\14\7\4\0\2\7\5\0\1\7"+
    "\1\0\1\7\12\0\6\7\1\0\4\7\1\50\1\51"+
    "\6\7\4\0\2\7\5\0\1\7\1\0\1\7\12\0"+
    "\3\7\1\52\2\7\1\0\14\7\4\0\2\7\5\0"+
    "\1\7\1\0\1\7\12\0\1\53\5\7\1\0\14\7"+
    "\4\0\2\7\5\0\1\7\1\0\1\7\12\0\6\7"+
    "\1\0\4\7\1\54\7\7\4\0\2\7\5\0\1\7"+
    "\1\0\1\7\12\0\1\7\1\55\2\7\1\56\1\7"+
    "\1\0\14\7\4\0\2\7\5\0\1\7\1\0\1\7"+
    "\12\0\6\7\1\0\2\7\1\57\11\7\4\0\2\7"+
    "\5\0\1\7\1\0\1\7\12\0\6\7\1\0\4\7"+
    "\1\60\7\7\4\0\2\7\5\0\1\7\1\0\1\7"+
    "\12\0\3\7\1\61\2\7\1\0\14\7\4\0\2\7"+
    "\5\0\1\7\1\0\1\7\12\0\1\62\5\7\1\0"+
    "\14\7\4\0\2\7\5\0\1\7\1\0\1\7\12\0"+
    "\4\7\1\63\1\7\1\0\11\7\1\64\2\7\4\0"+
    "\2\7\5\0\1\7\1\0\1\7\12\0\6\7\1\0"+
    "\3\7\1\65\10\7\4\0\2\7\5\0\1\7\1\0"+
    "\1\7\12\0\2\7\1\66\3\7\1\0\4\7\1\67"+
    "\7\7\4\0\2\7\5\0\1\70\1\71\46\0\7\46"+
    "\1\0\43\46\3\0\1\7\1\0\1\7\12\0\3\7"+
    "\1\72\2\7\1\0\10\7\1\73\3\7\4\0\1\74"+
    "\1\7\5\0\1\7\1\0\1\7\12\0\6\7\1\0"+
    "\6\7\1\75\5\7\4\0\2\7\5\0\1\7\1\0"+
    "\1\7\12\0\4\7\1\76\1\7\1\0\14\7\4\0"+
    "\2\7\5\0\1\7\1\0\1\7\12\0\5\7\1\77"+
    "\1\0\14\7\4\0\2\7\5\0\1\7\1\0\1\7"+
    "\12\0\6\7\1\0\1\100\13\7\4\0\2\7\5\0"+
    "\1\7\1\0\1\7\12\0\2\7\1\101\3\7\1\0"+
    "\14\7\4\0\2\7\5\0\1\7\1\0\1\7\12\0"+
    "\6\7\1\0\1\102\13\7\4\0\2\7\5\0\1\7"+
    "\1\0\1\7\12\0\4\7\1\103\1\7\1\0\14\7"+
    "\4\0\2\7\5\0\1\7\1\0\1\7\12\0\6\7"+
    "\1\0\12\7\1\104\1\7\4\0\2\7\5\0\1\7"+
    "\1\0\1\7\12\0\6\7\1\0\4\7\1\105\7\7"+
    "\4\0\2\7\5\0\1\7\1\0\1\7\12\0\6\7"+
    "\1\0\14\7\4\0\1\7\1\106\5\0\1\7\1\0"+
    "\1\7\12\0\6\7\1\0\3\7\1\107\10\7\4\0"+
    "\2\7\5\0\1\70\1\45\51\0\1\7\1\0\1\7"+
    "\12\0\4\7\1\110\1\7\1\0\14\7\4\0\2\7"+
    "\5\0\1\7\1\0\1\7\12\0\6\7\1\0\4\7"+
    "\1\111\7\7\4\0\2\7\5\0\1\7\1\0\1\7"+
    "\12\0\5\7\1\112\1\0\14\7\4\0\2\7\5\0"+
    "\1\7\1\0\1\7\12\0\6\7\1\0\7\7\1\113"+
    "\4\7\4\0\2\7\5\0\1\7\1\0\1\7\12\0"+
    "\6\7\1\0\13\7\1\114\4\0\2\7\5\0\1\7"+
    "\1\0\1\7\12\0\5\7\1\115\1\0\14\7\4\0"+
    "\2\7\5\0\1\7\1\0\1\7\12\0\6\7\1\0"+
    "\4\7\1\116\7\7\4\0\2\7\5\0\1\7\1\0"+
    "\1\7\12\0\2\7\1\117\3\7\1\0\14\7\4\0"+
    "\2\7\5\0\1\7\1\0\1\7\12\0\6\7\1\0"+
    "\4\7\1\120\7\7\4\0\2\7\5\0\1\7\1\0"+
    "\1\7\12\0\6\7\1\0\1\121\13\7\4\0\2\7"+
    "\5\0\1\7\1\0\1\7\12\0\6\7\1\0\4\7"+
    "\1\122\7\7\4\0\2\7\5\0\1\7\1\0\1\7"+
    "\12\0\2\7\1\123\3\7\1\0\14\7\4\0\2\7"+
    "\5\0\1\7\1\0\1\7\12\0\1\124\5\7\1\0"+
    "\14\7\4\0\2\7\5\0\1\7\1\0\1\7\12\0"+
    "\5\7\1\125\1\0\14\7\4\0\2\7\5\0\1\7"+
    "\1\0\1\7\12\0\5\7\1\126\1\0\14\7\4\0"+
    "\2\7\5\0\1\7\1\0\1\7\12\0\1\7\1\127"+
    "\4\7\1\0\14\7\4\0\2\7\5\0\1\7\1\0"+
    "\1\7\12\0\1\7\1\130\4\7\1\0\14\7\4\0"+
    "\2\7\5\0\1\7\1\0\1\7\12\0\5\7\1\131"+
    "\1\0\14\7\4\0\2\7\5\0\1\7\1\0\1\7"+
    "\12\0\1\7\1\132\4\7\1\0\14\7\4\0\2\7"+
    "\5\0\1\7\1\0\1\7\12\0\2\7\1\133\3\7"+
    "\1\0\14\7\4\0\2\7\5\0\1\7\1\0\1\7"+
    "\12\0\6\7\1\0\4\7\1\134\7\7\4\0\2\7"+
    "\5\0\1\7\1\0\1\7\12\0\6\7\1\0\3\7"+
    "\1\135\10\7\4\0\2\7\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2408];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\4\1\10\11\5\1\1\11\7\1\4\11"+
    "\1\1\2\11\24\1\1\0\44\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol mkSymbol(int id) {
        return new Symbol(id, yyline, yycolumn);
    }

    private Symbol mkSymbol(int id, Object val) {
        return new Symbol(id, yyline, yycolumn, val);
    }

    public int getChar() {
	return yychar + 1;
    }

    public int getColumn() {
    	return yycolumn + 1;
    }

    public int getLine() {
	return yyline + 1;
    }

    public String getText() {
	return yytext();
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FractalLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public FractalLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, FractalException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { return mkSymbol(sym.RPAREN);
          }
        case 43: break;
        case 22: 
          { // INTEGER
	       		 return mkSymbol(sym.REAL, 
			 	         new Double(yytext()));
          }
        case 44: break;
        case 15: 
          { return mkSymbol(sym.COMMA);
          }
        case 45: break;
        case 36: 
          { return mkSymbol(sym.SELF);
          }
        case 46: break;
        case 39: 
          { return mkSymbol(sym.RENDER);
          }
        case 47: break;
        case 11: 
          { return mkSymbol(sym.ISGREATER);
          }
        case 48: break;
        case 25: 
          { return mkSymbol(sym.FORWARD);
          }
        case 49: break;
        case 30: 
          { return mkSymbol(sym.NOT);
          }
        case 50: break;
        case 29: 
          { return mkSymbol(sym.AND);
          }
        case 51: break;
        case 26: 
          { return mkSymbol(sym.BACK);
          }
        case 52: break;
        case 6: 
          { return mkSymbol(sym.DIV);
          }
        case 53: break;
        case 1: 
          { // Unknown token (leave this in the last position)
    			  throw new FractalLexerException(yytext(), getLine(),
							  getColumn());
          }
        case 54: break;
        case 34: 
          { return mkSymbol(sym.HOME);
          }
        case 55: break;
        case 18: 
          { return mkSymbol(sym.LBRACE);
          }
        case 56: break;
        case 28: 
          { return mkSymbol(sym.PENUP);
          }
        case 57: break;
        case 10: 
          { return mkSymbol(sym.MOD);
          }
        case 58: break;
        case 3: 
          { // skip whitespace
          }
        case 59: break;
        case 13: 
          { return mkSymbol(sym.ASSIGN);
          }
        case 60: break;
        case 21: 
          { return mkSymbol(sym.SEQUENCE);
          }
        case 61: break;
        case 37: 
          { return mkSymbol(sym.RIGHT);
          }
        case 62: break;
        case 33: 
          { return mkSymbol(sym.LEFT);
          }
        case 63: break;
        case 35: 
          { return mkSymbol(sym.SAVE);
          }
        case 64: break;
        case 16: 
          { return mkSymbol(sym.LPAREN);
          }
        case 65: break;
        case 23: 
          { // skip line comments
          }
        case 66: break;
        case 5: 
          { // IDENTIFIERS
	       		 return mkSymbol(sym.ID, yytext());
          }
        case 67: break;
        case 19: 
          { return mkSymbol(sym.RBRACE);
          }
        case 68: break;
        case 14: 
          { return mkSymbol(sym.COLON);
          }
        case 69: break;
        case 20: 
          { return mkSymbol(sym.COMPOSE);
          }
        case 70: break;
        case 31: 
          { return mkSymbol(sym.DEFINE);
          }
        case 71: break;
        case 12: 
          { return mkSymbol(sym.ISLESS);
          }
        case 72: break;
        case 9: 
          { return mkSymbol(sym.MUL);
          }
        case 73: break;
        case 38: 
          { return mkSymbol(sym.CLEAR);
          }
        case 74: break;
        case 7: 
          { return mkSymbol(sym.PLUS);
          }
        case 75: break;
        case 27: 
          { return mkSymbol(sym.PENDOWN);
          }
        case 76: break;
        case 24: 
          { return mkSymbol(sym.OR);
          }
        case 77: break;
        case 42: 
          { return mkSymbol(sym.FRACTAL);
          }
        case 78: break;
        case 8: 
          { return mkSymbol(sym.MINUS);
          }
        case 79: break;
        case 41: 
          { return mkSymbol(sym.RESTORE);
          }
        case 80: break;
        case 4: 
          { // INTEGER
	       		 return mkSymbol(sym.INT, 
			 	         new Integer(yytext()));
          }
        case 81: break;
        case 40: 
          { return mkSymbol(sym.REPEAT);
          }
        case 82: break;
        case 2: 
          { //skip newline
          }
        case 83: break;
        case 32: 
          { return mkSymbol(sym.END);
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 	return new Symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
