
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 08 13:59:43 EST 2017
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENDOWN = 34;
  public static final int LPAREN = 4;
  public static final int REPEAT = 10;
  public static final int INT = 37;
  public static final int RENDER = 11;
  public static final int ISLESS = 23;
  public static final int FORWARD = 31;
  public static final int MINUS = 18;
  public static final int RPAREN = 5;
  public static final int DEFINE = 16;
  public static final int NOT = 28;
  public static final int AND = 27;
  public static final int OR = 26;
  public static final int COMMA = 8;
  public static final int DIV = 20;
  public static final int PLUS = 17;
  public static final int ASSIGN = 24;
  public static final int ID = 39;
  public static final int FRACTAL = 2;
  public static final int LEFT = 29;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SELF = 9;
  public static final int MUL = 19;
  public static final int HOME = 35;
  public static final int MOD = 21;
  public static final int REAL = 38;
  public static final int COLON = 25;
  public static final int LBRACE = 6;
  public static final int COMPOSE = 14;
  public static final int SAVE = 12;
  public static final int ISGREATER = 22;
  public static final int CLEAR = 36;
  public static final int RBRACE = 7;
  public static final int PENUP = 33;
  public static final int END = 3;
  public static final int SEQUENCE = 15;
  public static final int BACK = 32;
  public static final int RIGHT = 30;
  public static final int RESTORE = 13;
}

